[package]
name = "proc_qq_template"
version = "0.1.0"
edition = "2021"

[dependencies]
proc_qq = { path = "../proc_qq" }
anyhow = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
lazy_static = "1"
regex = "1"
