[package]
name = "proc_qq"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
futures="0.3"
reqwest = "0"
proc_qq_codegen = { path = "../proc_qq_codegen" }
bytes = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0"
ricq = "0.1"
ricq-core = "0.1"
anyhow = "1"
serde = "1"
serde_json = "1"
serde_derive = "1"

[lib]
